name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          Thanks for your Pull Request! It's great to see your interest in contributing to this project.

          This repository is a "subtree split": an automated copy of a subdirectory of the main repository.
          It does not accept Pull Requests directly.

          Accordingly, this PR will be closed. Instead, please open your PR on the main repository:
          https://github.com/outboardphp/outboard

